dist: trusty
language: python
notifications:
  email: false
cache:
  pip: true
matrix:
  include:
    - python: 2.7
    - os: osx
      osx_image: xcode9.1
      language: generic
      before_install:
      - virtualenv env
      - source env/bin/activate
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
install:
  - pip install nose flake8 tensorflow==1.4.0
  - pip install -e .
script:
  - flake8 deepmoji examples scripts tests --ignore=F403,E501,E123,E128,E402,F401,F841,F811
  - python scripts/download_weights.py
  - cd tests
  - nosetests -v
